### ISSUE TITLE
Custom styles for chapters

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1629]
https://www.scribblehub.com/read/170911-i-reincarnated-as-an-immortal-caterpillar/chapter/171285/

![image](https://user-images.githubusercontent.com/11484976/192139197-3b6ba3da-8b40-488f-9444-bac49cbd216e.png)
![image](https://user-images.githubusercontent.com/11484976/192139233-116f16ce-15de-49be-bee8-38b8f7de85b6.png)
![image](https://user-images.githubusercontent.com/11484976/192139253-e126057c-2cd0-4e05-b959-c15b8829e864.png)

@dipu-bd Is there a way to make its own style for table for scribblehub crawler? 
Can I add a style to the table tag while downloading the chapter?

**Comment by idMysteries** [comment]
<table style=""> ?

**Comment by idMysteries** [comment]
``` css
#chp_contents table {
    max-width: 100%!important;
    margin-bottom: 1.5em;
    margin-left: auto;
    margin-right: auto;
    height: 100%!important;
    background-color: #374558;
    color: #bfc4c9;
    border-collapse: collapse;
    border-color: #000;
}
```
